HEIGHT : 256
WIDTH : 256

PADDED_HEIGHT : 588
PADDED_WIDTH : 604

INPUT_CHANNELS : 1
OUTPUT_CHANNELS : 4
NUM_BSCANS_PER_VOLUME : 128

# Hyperparameters
BATCH_SIZE : 2
BUFFER_SIZE : 1000
EPOCHS : 200

# class labels
BACKGROUND_LABEL : 0
IRF_LABEL : 1
SRF_LABEL : 2
PED_LABEL : 3

